### ISSUE TITLE
Error after setting up

### ISSUE THREAD

**Issue by bk-marcin-poholski** [rafalolszewski94/vue3-smooth-scrollbar#1]
```
runtime-core.esm-bundler.js:2252 Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2252:10)
    at vue-router.esm-bundler.js:2127:38
```

It does not work.

**Comment by smallsun-lgtm** [comment]
same problem

**Comment by orafal-dev** [comment]
Not sure if you're still interested in using this package, but this should be fixed now.
